<a href="https://colab.research.google.com/github/saba020/Development-of-AI-Response-Validation-System-with-Hallucination-Detection-Assistance/blob/main/SQL_INTERVIEW_QUESTIONS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**SQL INTERVIEW QUESTIONS**

1.Creating Database

In [40]:
!pip install mysql-connector-python

Collecting mysql-connector-python
  Downloading mysql_connector_python-26.7.0-cp313-cp313-manylinux_2_28_x86_64.whl.metadata (11 kB)
Downloading mysql_connector_python-26.7.0-cp313-cp313-manylinux_2_28_x86_64.whl (21.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.7/21.7 MB 63.2 MB/s eta 0:00:00
Installing collected packages: mysql-connector-python
Successfully installed mysql-connector-python-26.7.0

2. IMPORTING LIBRARIES

In [ ]:
import sqlite3
import pandas as pd

3.CREATING TABLE OF STUDENT, COURSES AND INSERTING VALUES

In [14]:


# Create an in-memory SQLite database
connection = sqlite3.connect(":memory:")

# Create a cursor
cursor = connection.cursor()

# Enable foreign key enforcement
cursor.execute("PRAGMA foreign_keys = ON")

# Create tables and insert sample data
cursor.executescript("""
CREATE TABLE Students (
    student_id INTEGER PRIMARY KEY,
    student_name TEXT NOT NULL,
    age INTEGER,
    city TEXT,
    marks REAL
);

CREATE TABLE Courses (
    course_id INTEGER PRIMARY KEY,
    course_name TEXT NOT NULL,
    fee REAL NOT NULL
);

INSERT INTO Students VALUES
(1, 'Amit', 20, 'Kolkata', 85),
(2, 'Priya', 21, 'Delhi', 92),
(3, 'Rahul', 19, 'Mumbai', 76),
(4, 'Sneha', 22, 'Kolkata', 88),
(5, 'Arjun', 20, 'Chennai', 67),
(6, 'Neha', 21, 'Delhi', 95);

INSERT INTO Courses VALUES
(101, 'Python', 5000),
(102, 'SQL', 4000),
(103, 'Data Science', 8000),
(104, 'Web Development', 6000);
""")
def run(query):
    """Run a SQL query and show the result as a table."""
    return pd.read_sql_query(query, connection)

#
run("SELECT * FROM Students")

   student_id student_name  age     city  marks
0           1         Amit   20  Kolkata   85.0
1           2        Priya   21    Delhi   92.0
2           3        Rahul   19   Mumbai   76.0
3           4        Sneha   22  Kolkata   88.0
4           5        Arjun   20  Chennai   67.0
5           6         Neha   21    Delhi   95.0

4.INSERTING NEW STUDENT IN STUDENT TABLE

In [16]:
run("""
SELECT * FROM Students
WHERE student_id = 1
""")

cursor.execute("""
INSERT INTO Students
VALUES (7, 'Kiran', 23, 'Pune', 81)
""")
connection.commit()

run("SELECT * FROM Students WHERE student_id = 7;")

   student_id student_name  age  city  marks
0           7        Kiran   23  Pune   81.0

5.DISPLAYING UPDATED TABLE WITH NEW STUDENT

In [17]:
run("SELECT * FROM Students" )

   student_id student_name  age     city  marks
0           1         Amit   20  Kolkata   85.0
1           2        Priya   21    Delhi   92.0
2           3        Rahul   19   Mumbai   76.0
3           4        Sneha   22  Kolkata   88.0
4           5        Arjun   20  Chennai   67.0
5           6         Neha   21    Delhi   95.0
6           7        Kiran   23     Pune   81.0

6.Find students from Delhi and Kolkata.

In [18]:
run("SELECT * FROM Students WHERE city IN ('Delhi', 'Kolkata');")

   student_id student_name  age     city  marks
0           1         Amit   20  Kolkata   85.0
1           2        Priya   21    Delhi   92.0
2           4        Sneha   22  Kolkata   88.0
3           6         Neha   21    Delhi   95.0

7.Find students scoring more than 80.

In [39]:
run("SELECT * FROM Students WHERE marks > 50;")

   student_id student_name  age     city  marks
0           1         Amit   20  Kolkata   85.0
1           2        Priya   21    Delhi   92.0
2           3        Rahul   19   Mumbai   76.0
3           4        Sneha   22  Kolkata   88.0
4           5        Arjun   20  Chennai   67.0
5           6         Neha   21    Delhi   95.0

8. Find students from Kolkata.

In [31]:
run("SELECT * FROM Students WHERE city = 'Kolkata';")

   student_id student_name  age     city  marks
0           1         Amit   20  Kolkata   85.0
1           4        Sneha   22  Kolkata   88.0

9. Find students aged between 20 and 22

In [41]:
run("SELECT * FROM Students WHERE age BETWEEN 20 AND 22;")

   student_id student_name  age     city  marks
0           1         Amit   20  Kolkata   85.0
1           2        Priya   21    Delhi   92.0
2           4        Sneha   22  Kolkata   88.0
3           5        Arjun   20  Chennai   67.0
4           6         Neha   21    Delhi   95.0

	10.Count all students

In [42]:
run("SELECT COUNT(*) AS total_students FROM Students;")

   total_students
0               6

11. Count students in each city

In [44]:
run("SELECT city, COUNT(*) AS total FROM Students GROUP BY city;")

      city  total
0  Chennai      1
1    Delhi      2
2  Kolkata      2
3   Mumbai      1

12. LEFT JOIN — display all students and their courses.

In [49]:
run("SELECT s.student_name, c.course_name FROM Students s LEFT JOIN Courses c ON s.student_id = c.course_id;")

  student_name course_name
0         Amit        None
1        Priya        None
2        Rahul        None
3        Sneha        None
4        Arjun        None
5         Neha        None